apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxc-authenticity-collector
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cxc-authenticity-collector
  template:
    metadata:
      labels:
        app: cxc-authenticity-collector
    spec:
      containers:
        - name: cxc-authenticity-collector
          image: iotaledger/cxc-authenticity-collector:v0.1.0
          imagePullPolicy: Always
          command:
          - npm
          - run
          - start:prod
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "250Mi"
              cpu: "500m"
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 3000
          env:
            - name: "API_KEY"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: SLU_STATUS_API_KEY
            - name: "DATABASE_URL"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: DATABASE_URL
            - name: "DATABASE_NAME"
              value: "authenticity-collector"
            - name: "PROVE_OF_OWNERSHIP_URL"
              value: http://cxc-proof-of-ownership:3000/api/v1/ownership/prove
            - name: "IS_API_KEY"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: API_KEY
            - name: "IS_API_URL"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: INTEGRATION_SERVICE
            - name: "COLLECTOR_DID"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: COLLECTOR_DID
            - name: "COLLECTOR_SECRET"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: COLLECTOR_SECRET
            - name: "AUTH_PROVE_EXPIRATION"
              value: "120000"
            - name: "JWT_SECRET"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: JWT_SECRET
            - name: "MPOWER_CONNECTOR_URL"
              valueFrom:
                configMapKeyRef:
                  name: cxc-config
                  key: MPOWER_CONNECTOR_URL
          ports:
            - name: http
              protocol: TCP
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cxc-authenticity-collector
  labels:
    app: cxc-authenticity-collector    
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cxc-authenticity-collector
