# This is a basic workflow to help you get started with Actions

name: Build Api

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master, develop ]
    paths: 
      - "api/**"
      - ".github/workflows/build-api.yaml"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Setup node and build api
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
      # build local package in advance
      - name: Build shared modules
        run: |
          cd api/shared-modules
          npm install
          npm run build
      - name: Build api
        run: |
          cd api
          npm install
          npm run build
